name: veripol
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.2.2
  firebase_auth: ^3.3.10
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  google_sign_in: ^5.2.4
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  syncfusion_flutter_charts: ^19.4.56
  url_launcher: ^6.0.20
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "veripol_launcher_icon"
  image_path: "assets/icons/VeriPol_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/data/locations.json
    - assets/data/candidates/

  fonts:
    - family: MountainScript
      fonts:
        - asset: assets/fonts/Mountain Script.ttf
